### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by tlot02** [tlot02/fbcFairdale#1]
## TODO
- [ ] create basic css stylings
- [ ] Create landing page
- [ ] create sub pages
